---
language: php
dist: trusty
group: edge
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-3.15
  - hhvm-nightly

before_script:
  - phpenv config-rm xdebug.ini || true

script: "php test/cli.php"
