<?php

//CONVERSION MODES
define('TBX_CONVERT_UNKNOWN',	0);
define('TBX_CONVERT_DEFAULT',	1);
define('TBX_CONVERT_SPECIAL',	2);
define('TBX_CONVERT_DATE',		3);
define('TBX_CONVERT_FORMAT',	4);
define('TBX_CONVERT_FUNCTION',	5);
define('TBX_CONVERT_SELECTED',	6);
define('TBX_CONVERT_CHECKED',	7);


//DATA SOURCE TYPES
define('TBX_DS_ARRAY',			0);
define('TBX_DS_NUMBER',			1);
define('TBX_DS_TEXT',			2);
define('TBX_DS_PUDL',			3);
define('TBX_DS_ITERATOR',		4);


//SUBTYPES
define('TBX_DS_SUB0',			0);
define('TBX_DS_SUB1',			1);
define('TBX_DS_SUB2',			2);
define('TBX_DS_SUB3',			3);


//MAGNETS
define('TBX_MAGNET_NONE',		0);
define('TBX_MAGNET_ZERO',		1);
define('TBX_MAGNET_TAG',		2);
define('TBX_MAGNET_PLUS',		3);
define('TBX_MAGNET_SUFFIX',		4);
define('TBX_MAGNET_PREFIX',		5);
define('TBX_MAGNET_ATTADD',		6);
define('TBX_MAGNET_ATTR',		7);
define('TBX_MAGNET_IFEMPTY',	8);
define('TBX_MAGNET_NBSP',		9);
